version: "2"
services:
    dinner-backend:
        image: challisa/dinner.me.backend.new
        container_name: dinner.me.backend.new
        ports:
            - "8000:8000"
        build:
            context: ./backend
            args:
                MONGO_USERNAME: ${MONGO_USERNAME}
                MONGO_PASSWORD: ${MONGO_PASSWORD}
        env_file:
            - .env
        volumes:
            - ./backend:/opt/working
        entrypoint: uvicorn api:api --reload --host 0.0.0.0 --port 8000

    dinner-frontend:
        image: challisa/dinner.me.frontend.new
        container_name: dinner.me.frontend.new
        ports:
            - 3000:3000
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next
